export const bgColors = {
  primary: "bg-Primary",
  secondary: "bg-Secondary",
  success: "bg-Success",
  warning: "bg-Warning",
  danger: "bg-Danger",
  red: "bg-red-500",
  orange: "bg-orange-500",
  yellow: "bg-yellow-500",
  green: "bg-green-500",
  blue: "bg-blue-500",
  purple: "bg-purple-500",
  pink: "bg-pink-500",
  basic: "bg-Basic",
  white: "bg-white !border-gray !border-2",
  gray: "bg-gray",
  black: "bg-black",
};

export const borderColors = {
  primary: "border-Primary !border-2 !bg-white",
  secondary: "border-Secondary !border-2 !bg-white",
  success: "border-Success !border-2 !bg-white",
  warning: "border-Warning !border-2 !bg-white",
  danger: "border-Danger !border-2 !bg-white",
  red: "border-red-500 !border-2 !bg-white",
  orange: "border-orange-500 !border-2 !bg-white",
  yellow: "border-yellow-500 !border-2 !bg-white",
  green: "border-green-500 !border-2 !bg-white",
  blue: "border-blue-500 !border-2 !bg-white",
  purple: "border-purple-500 !border-2 !bg-white",
  pink: "border-pink-500 !border-2 !bg-white",
  basic: "border-Basic !border-2 !bg-white",
  white: "bg-white !border-gray !border-2",
  gray: "border-gray !border-2 !bg-white",
  black: "border-black !border-2 !bg-white",
};
