import Quickmenu from "@components/Quickmenu/Quickmenu";

export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>
        {children}
        <div className="hidden xl:block">
          <Quickmenu />
        </div>
      </div>
    </>
  );
}
