import "./globals.css";
import Header from "@components/Layout/Header";
import Footer from "@components/Footer/Footer";
import DarkModeStatus from "@components/DarkModeStatus/DarkModeStatus";

export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <meta
          name="google-site-verification"
          content="b_AwjVpFGRsC_D3vMWGMDRUq7iCrzZtKE2riNEA40vo"
        />
      </head>
      <body>
        <DarkModeStatus>
          <Header />

          <div>
            <div>{children}</div>
          </div>
          <div className="mt-80 flex items-center justify-center">
            <Footer />
          </div>
        </DarkModeStatus>
      </body>
    </html>
  );
}
