// app/layout.tsx
import "./globals.css";
import SideBar from "@components/Layout/SideBar";
import Header from "@components/Layout/Header";
import Footer from "@components/Footer/Footer";
import DarkModeStatus from "@components/DarkModeStatus/DarkModeStatus";

export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <DarkModeStatus>
          <Header />
          <section className="fixed z-0 mt-[90px] hidden h-[calc(100%-90px)] w-[250px] bg-white xl:block">
            <SideBar />
          </section>
          <div className="flex justify-center pt-[90px] md:px-4 xl:ml-[300px]">
            <div className="max-w-full">{children}</div>
          </div>
          <div className="flex items-center justify-center">
            <Footer />
          </div>
        </DarkModeStatus>
      </body>
    </html>
  );
}
