import UserPagePrevButton from "@components/Layout/UserPagePrevButton";
export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full">
      <div className="flex">
        <section className="fixed h-[calc(100%-120px)] w-[80px] bg-red-100">
          <UserPagePrevButton />
        </section>
        <div className="ml-[85px] w-[calc(100%-440px)] bg-yellow-100">
          {children}
        </div>
        <div className="fixed right-0 h-[calc(100%-120px)] w-[350px] overflow-y-auto"></div>
      </div>
    </div>
  );
}
