import UserPagePrevButton from "@components/Layout/UserPagePrevButton";
export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full">
      <section className="fixed left-3 top-28 h-[calc(100%-120px)]">
        <UserPagePrevButton />
      </section>
      <div className="w-full bg-yellow-200">{children}</div>
    </div>
  );
}
