export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>
        <div className="flex justify-center pt-[80px]">{children}</div>
      </div>
    </>
  );
}
