import Image from "next/image";
export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>
        <Image
          src="/Componique.svg"
          alt="로고 텍스트"
          width={350}
          className="fixed left-1/2 top-5 z-[999] -translate-x-1/2"
          height={54}
        />
        <div className="flex justify-center pt-[80px]">{children}</div>
      </div>
    </>
  );
}
