import UserPageLogoText from "@components/Layout/UserPageLogoText";
import UserPageLeftSidebar from "@components/Layout/UserPageLeftSidebar";
export const metadata = {
  title: "Componique",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="select-none">
        <UserPageLogoText />
        <div className="flex justify-center pt-[80px]">
          <div className="w-full">
            <section className="fixed left-4 top-26 h-[calc(100%-120px)] w-[230px] rounded-l-2xl bg-[#D8EAF8] shadow-lg dark:bg-[#353F4A]">
              <UserPageLeftSidebar />
            </section>
            <div className="w-full">{children}</div>
          </div>
        </div>
      </div>
    </>
  );
}
